import Head from "next/head";
import Header from "../components/Header";
import { Nav } from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu (First Next Project)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Nav />
      <Results results={results} />
      <h3 className="text-center tracking-widest group mb-2 cursor-default select-none">
        First Next Project ©
        <a
          className="group-hover:animate-bounce h-8 mb-1 inline-block group-hover:font-bold transition-all duration-300"
          target="_blank"
          rel="noreferrer"
          href="https://www.linkedin.com/in/feriani-mahdi-996a0521a/"
        >
          Feriani Mahdi
        </a>{" "}
        ❤
      </h3>
    </div>
  );
}
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      results: request.results,
    },
  };
}
